routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ProductViewController;
use App\Http\Controllers\CheckoutController;
use App\Http\Controllers\ChangePasswordController;
use App\Http\Controllers\UpdateProfileController;
use App\Http\Controllers\StripeController;
use App\Models\Product;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    $products = Product::orderBy("created_at",'desc')->take(8)->get();
    return view('home',compact('products'));
});

Auth::routes();
Route::get("admin",function(){
    return redirect("dashboard");
});
// change password
Route::resource('change-password', ChangePasswordController::class);
// update profile
Route::get('/update-profile/{user}',  [UpdateProfileController::class, 'editProfile'])->name("profile.edit");
Route::patch('/update-profile/{user}',  [UpdateProfileController::class, 'updateProfile'])->name('profile.update');

// routes for make ordering front pages
Route::get('/checkout', [CheckoutController::class, 'checkout'])->name('cart.checkout');
Route::get('add-to-cart/{id}', [ProductViewController::class, 'addToCart'])->name('add.to.cart');
Route::patch('update-cart', [ProductViewController::class, 'update'])->name('update.cart');
Route::delete('remove-from-cart', [ProductViewController::class, 'remove'])->name('remove.from.cart');
Route::get('/home',function(){
    return redirect('/');
})->name('home');
// route for admin
Route::resource('product-order', App\Http\Controllers\ProductOrderController::class);
Route::resource('brand', App\Http\Controllers\ModelController::class);
Route::resource('dashboard', App\Http\Controllers\DashboardController::class);
Route::resource('product-list', ProductViewController::class);
Route::resource('products', App\Http\Controllers\ProductController::class);
Route::resource('cart', App\Http\Controllers\CartController::class);
Route::resource('contact-us', App\Http\Controllers\ContactController::class);
Route::resource('contacts', App\Http\Controllers\ContactBackEndController::class);
Route::resource('users', App\Http\Controllers\UserController::class);
   
Route::get('stripe', [StripeController::class, 'stripe']);
Route::post('stripe', [StripeController::class, 'stripePost'])->name('stripe.post');

app/Models/Contact.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Contact extends Model
{
    use HasFactory;
    protected $table='contacts';
    protected $primarykey='id';
    protected $fillable = [
        'username','email','subject','message',
    ];
}

app/Http/Controllers/ContactController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Validator;
use App\Models\Contact;
use Mail;
use App\Mail\SendMail;

class ContactController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view("pages.fronts.contact");
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validator = Validator::make($request->all(),[
            'username' => 'required',
            'email' => 'required',
            'subject' => 'required',
            'message' => 'required'
        ]);
        if ($validator->fails()) {
            return redirect()->back()->withErrors($validator)->withInput($request->input());
        }

        $username = $request->username;
        $email = $request->email;
        $subject = $request->subject;
        $message = $request->message;

        // Mail::to('bunsinnanh22@gmail.com')->send(new SendMail($username,$email,$subject,$message));

        Contact::create($request->all());

        return redirect()->back()->with("success","Thank you for your contaction us!");
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/pages/admin/contact/contact.blade.php
@extends('layouts.dashboard')
@section('dashboard')
    <div class="row justify-content-center">
        <div class="col-md-5">
            @if ($message = Session::get('success'))
                <div class="alert alert-success alert-block">
                    <strong>{{ $message }}</strong>
                </div>
            @endif
            @if ($message = Session::get('error'))
                <div class="alert alert-danger alert-block">
                    <strong>{{ $message }}</strong>
                </div>
            @endif
        </div>
    </div>
    <div class="row">
        <div class="col-md-10">
            <h4>Contactor Listing</h4>
        </div>
    </div>
    <table class="table table-striped table-horvered table-bordered mt-3" id="datatablesSimple">
        <thead>
            <tr>
                <th>#</th>
                <th>Username</th>
                <th>Email</th>
                <th>Subject</th>
                <th>Message</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($contacts as $contact)
                <tr>
                    <td width="5%">{{ $index++ }}</td>
                    <td width="20%">
                        <span>{{ $contact->username }}</span>
                    </td>
                    <td width="20%">
                        <span>{{ $contact->email }}</span>
                    </td>
                    <td width="20%">
                        <span>{{ $contact->subject }}</span>
                    </td>
                    <td width="20%">
                        <span>{{ $contact->message }}</span>
                    </td>
                    <td width="10%">
                        <a href="{{ route("contacts.show",$contact->id) }}">
                            <i class="fas fa-eye fa-fw text-primary"></i>
                        </a>
                    </td>
                </tr>
            @endforeach
        </tbody>
    </table>
@endsection

resources/views/pages/admin/contact/view.blade.php
@extends('layouts.dashboard')
@section('dashboard')
    <div class="container">
        <div class="card">
            <div class="card-body">
                <h3>View Contact</h3><hr>
                <a href="{{ url("contacts") }}" class="btn btn-sm btn-warning">
                    <i class="fa fa-arrow-left"></i>Back
                </a>
                <div class="row justify-content-center">
                    <div class="col-md-6">
                        <ul class="list-group">
                            <li class="list-group-item d-flex justify-content-between align-items-center">
                              Username:
                            <span>{{ $contact->username }}</span>
                            </li>
                            <li class="list-group-item d-flex justify-content-between align-items-center">
                              Email:
                              <span>{{ $contact->email }}</span>
                            </li>
                            <li class="list-group-item d-flex justify-content-between align-items-center">
                              Subject:
                              <span>{{ $contact->subject }}</span>
                            </li>
                            <li class="list-group-item d-flex justify-content-between align-items-center">
                              Message:
                              <span>{{ $contact->message }}</span>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection