routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ProductViewController;
use App\Http\Controllers\CheckoutController;
use App\Http\Controllers\ChangePasswordController;
use App\Http\Controllers\UpdateProfileController;
use App\Http\Controllers\StripeController;
use App\Models\Product;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    $products = Product::orderBy("created_at",'desc')->take(8)->get();
    return view('home',compact('products'));
});

Auth::routes();
Route::get("admin",function(){
    return redirect("dashboard");
});
// change password
Route::resource('change-password', ChangePasswordController::class);
// update profile
Route::get('/update-profile/{user}',  [UpdateProfileController::class, 'editProfile'])->name("profile.edit");
Route::patch('/update-profile/{user}',  [UpdateProfileController::class, 'updateProfile'])->name('profile.update');

// routes for make ordering front pages
Route::get('/checkout', [CheckoutController::class, 'checkout'])->name('cart.checkout');
Route::get('add-to-cart/{id}', [ProductViewController::class, 'addToCart'])->name('add.to.cart');
Route::patch('update-cart', [ProductViewController::class, 'update'])->name('update.cart');
Route::delete('remove-from-cart', [ProductViewController::class, 'remove'])->name('remove.from.cart');
Route::get('/home',function(){
    return redirect('/');
})->name('home');
// route for admin
Route::resource('product-order', App\Http\Controllers\ProductOrderController::class);
Route::resource('brand', App\Http\Controllers\ModelController::class);
Route::resource('dashboard', App\Http\Controllers\DashboardController::class);
Route::resource('product-list', ProductViewController::class);
Route::resource('products', App\Http\Controllers\ProductController::class);
Route::resource('cart', App\Http\Controllers\CartController::class);
Route::resource('contact-us', App\Http\Controllers\ContactController::class);
Route::resource('contacts', App\Http\Controllers\ContactBackEndController::class);
Route::resource('users', App\Http\Controllers\UserController::class);
   
Route::get('stripe', [StripeController::class, 'stripe']);
Route::post('stripe', [StripeController::class, 'stripePost'])->name('stripe.post');

app/Models/Brand.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Brand extends Model
{
    use HasFactory;
    protected $table='models';
    protected $primarykey='id';
    protected $fillable = [
        'name',
    ];

    // relationship one brand has many products
    public function products(){
        return $this->hasMany(Product::class);
    }
}

app/Models/Contact.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Contact extends Model
{
    use HasFactory;
    protected $table='contacts';
    protected $primarykey='id';
    protected $fillable = [
        'username','email','subject','message',
    ];
}

app/Models/Order.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Order extends Model
{
    use HasFactory;
    protected $table='orders';
    protected $primarykey='id';
    protected $fillable = [
        'amount','user_id',
        'transaction_id','card_cvc',
        'card_expiry_month',
        'card_expiry_year',
        'order_status',
        'card_holder_number',
        'card_holder_name'
    ];
        
    public function user()
    {
        return $this->belongsTo(User::class, 'user_id', 'id');
    }
}

app/Models/OrderItem.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class OrderItem extends Model
{
    use HasFactory;
    protected $table='order_items';
    protected $primarykey='id';
    protected $fillable = [
        'order_id','product_id','amount','quantity'
    ];
    
    public function order()
{
    return $this->belongsTo(Order::class, 'order_id', 'id');
}

public function product()
{
    return $this->belongsTo(Product::class, 'product_id', 'id');
}
}

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    use HasFactory;
    protected $table='products';
    protected $primarykey='id';
    protected $fillable = [
        'name','screen','price','image','color','type','ram','hard_disk','cpu','model_id'
    ];

    // // relationship many products belongs to many users
    // public function users(){
    //     return $this->belongsToMany(User::class,'user_id');
    // }
    // relationship many products belongs to one brand
    public function model(){
        return $this->belongsTo(Brand::class,'model_id');
    }
    
    public function orders()
    {
        return $this->belongsToMany(Order::class,'order_items');
    }
}

app/Models/Role.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Role extends Model
{
    use HasFactory;
    protected $table='roles';
    protected $primarykey='id';
    protected $fillable = [
        'role',
    ];

    // relationship one role have many users
    public function users(){
        return $this->hasMany(User::class);
    }

}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    // relationship role have many users belongs to one role
    
    public function role(){
        return $this->belongsTo(Role::class);
    }
     
    public function order(){
        return $this->belongsTo(OrderItem::class);
    }
    // // relationship many users belongs to many products
    // public function products(){
    //     return $this->belongsToMany(Product::class,'product_id');
    // }
    /**
     * The attributes that are mass assignable.
     *
     * @var string[]
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'phone',
        'role_id',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/ModelController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Brand;
use Validator;
use DB;
class ModelController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function __construct()
    {
        $this->middleware('auth');
        $this->middleware('role:admin');
    }
    public function index()
    {
        $index = 1;
        $models = Brand::orderBy("name",'asc')->get();
        return view("pages.admin.models.model",compact("index",'models'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view("pages.admin.models.add");
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validator = Validator::make($request->all(),[
            'name' => 'required',
        ]);  
        if ($validator->fails()) {
            return redirect()->back()->withErrors($validator)->withInput($request->input());
        }
        $exists = DB::table('models')->where('name',$request->input('name'))->exists();
        if ($exists) {
            return redirect()->back()->with('warning','Model name ready exists !!');
        }

        Brand::create($request->all());
        return redirect('brand')->with("success","Model created successfully!");
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $model = Brand::findOrFail($id);
        return view("pages.admin.models.edit",compact("model"));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $validator = Validator::make($request->all(),[
            'name' => 'required',
        ]);  
        if ($validator->fails()) {
            return redirect()->back()->withErrors($validator)->withInput($request->input());
        }

        $model = Brand::findOrFail($id);
        $model->name = $request->name;
        $model->save();

        return redirect("brand")->with("success","Model updated successfully!!");
    }
    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $model = Brand::findOrFail($id);
        $model->delete();
        return redirect()->back()->with('success','Model deleted successfully !');
    }
}

resources/views/pages/admin/models/add.blade.php
@extends('layouts.dashboard')
@section('dashboard')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-6">
                @if ($message = Session::get('warning'))
                    <div class="alert alert-warning alert-block">
                        <strong>{{ $message }}</strong>
                    </div>
                @endif
            </div>
        </div>
        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="card">
                    <div class="card-header">
                        <h4>Create New Model</h4>
                    </div>
                    <div class="card-body">
                        <form action="{{ route("brand.store") }}" method="post">
                            @csrf
                            @method("POST")
                            <div class="form-group mb-4">
                                <label for="name">Model Name</label>
                                <input type="text" name="name" id="name" class="form-control" 
                                placeholder="Model Name" value="{{ old("name") }}">
                                @if ($errors->has('name'))
                                    <span class="text-danger">
                                        <strong>{{ $errors->first('name') }}</strong>
                                    </span>
                                @endif
                            </div>
                            <div class="form-group">
                                <a href="{{ url("brand") }}" class="btn btn-secondary">Cancel</a>
                                <button type="submit" class="btn btn-success float-right">Create</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/pages/admin/models/edit.blade.php
@extends('layouts.dashboard')
@section('dashboard')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-6">
                @if ($message = Session::get('warning'))
                    <div class="alert alert-warning alert-block">
                        <strong>{{ $message }}</strong>
                    </div>
                @endif
            </div>
        </div>
        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="card">
                    <div class="card-header">
                        <h4>Edit Model</h4>
                    </div>
                    <div class="card-body">
                        <form action="{{ route("brand.update",$model->id) }}" method="post">
                            @csrf
                            @method("PATCH")
                            <div class="form-group mb-4">
                                <label for="name">Model Name</label>
                                <input type="text" name="name" id="name" class="form-control" 
                                placeholder="Model Name" value="{{ $model->name }}">
                                @if ($errors->has('name'))
                                    <span class="text-danger">
                                        <strong>{{ $errors->first('name') }}</strong>
                                    </span>
                                @endif
                            </div>
                            <div class="form-group">
                                <a href="{{ url("brand") }}" class="btn btn-secondary">Cancel</a>
                                <button type="submit" class="btn btn-success float-right">Update</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/pages/admin/models/model.blade.php
@extends('layouts.dashboard')
@section('dashboard')
    <div class="row justify-content-center">
        <div class="col-md-5">
            @if ($message = Session::get('success'))
                <div class="alert alert-success alert-block">
                    <strong>{{ $message }}</strong>
                </div>
            @endif
            @if ($message = Session::get('error'))
                <div class="alert alert-danger alert-block">
                    <strong>{{ $message }}</strong>
                </div>
            @endif
        </div>
    </div>
    <div class="row">
        <div class="col-md-10">
            <h4>Model Listing</h4>
        </div>
        <div class="col-md-2 mr-auto">
            <a href="{{ route("brand.create") }}" class="btn btn-sm btn-primary float-right">
                <i class="fa fa-plus-circle"></i> Add Model
            </a>
        </div>
    </div>
    <table class="table table-striped table-horvered table-bordered mt-3" id="datatablesSimple">
        <thead>
            <tr>
                <th>#</th>
                <th>Model Name</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($models as $model)
                <tr>
                    <td width="5%">{{ $index++ }}</td>
                    <td width="40%">
                        {{-- <img src="{{ asset("images/products/Samsung-Galaxy-s10plus.jpg") }}" alt="" width="5%"> --}}
                        <span>{{ $model->name }}</span>
                    </td>
                    <td width="10%">
                        {{-- <a href="#"><i class="fas fa-eye fa-fw text-primary"></i></a> --}}
                        <a href="#" data-toggle="modal" data-target="#delete-model"
                            data-id="{{ $model->id }}" data-name="{{ $model->name }}">
                            <i class="fas fa-trash-alt fa-fw text-danger"></i>
                        </a>
                        <a href="{{ route("brand.edit",$model->id) }}">
                            <i class="fas fa-pencil-alt fa-fw text-success"></i>
                        </a>
                    </td>
                </tr>
            @endforeach
        </tbody>
    </table>
    <div class="modal fade" id="delete-model" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <form action="" method="POST" id="form-delete-model" enctype="multipart/form-data">
                    @method('DELETE')
                    @csrf
                    <div class="modal-header">
                        <h4 class="modal-title" id="deleteModelLabel">Delete Model</h4>
                    </div>
                    <div class="modal-body">
                        <p>Do you sure to <b>delete</b> model name <b><span class="text-danger" id="model-name"></span></b>?</p>
                        <div class="text-center">
                            {{-- <img src="" alt="" width="50%" id="product-image" class="text-center"> --}}
                        </div>
                    </div>
                    <div class="modal-footer text-white">
                        <button type="button" class="btn btn-link waves-effect btn-success left" data-dismiss="modal">No</button>
                        <button type="submit" class="btn btn-link btn-danger waves-effect right">Yes</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection
@push('script')
    <script>
        $(document).ready(function(){
            $('#delete-model').on('show.bs.modal',function (event){
                var button = $(event.relatedTarget)
                var id = button.data('id');
                var modelName = button.data('name');
                // var proImage = button.data('image');
                var modal = $(this);
                var url ='{{ route("brand.destroy", "id") }}';
                $('#model-name').text(modelName);
                $('#form-delete-model').attr('action',url.replace('id', id));
            });
        });
    </script>
@endpush