routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ProductViewController;
use App\Http\Controllers\CheckoutController;
use App\Http\Controllers\ChangePasswordController;
use App\Http\Controllers\UpdateProfileController;
use App\Http\Controllers\StripeController;
use App\Models\Product;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    $products = Product::orderBy("created_at",'desc')->take(8)->get();
    return view('home',compact('products'));
});

Auth::routes();
Route::get("admin",function(){
    return redirect("dashboard");
});
// change password
Route::resource('change-password', ChangePasswordController::class);
// update profile
Route::get('/update-profile/{user}',  [UpdateProfileController::class, 'editProfile'])->name("profile.edit");
Route::patch('/update-profile/{user}',  [UpdateProfileController::class, 'updateProfile'])->name('profile.update');

// routes for make ordering front pages
Route::get('/checkout', [CheckoutController::class, 'checkout'])->name('cart.checkout');
Route::get('add-to-cart/{id}', [ProductViewController::class, 'addToCart'])->name('add.to.cart');
Route::patch('update-cart', [ProductViewController::class, 'update'])->name('update.cart');
Route::delete('remove-from-cart', [ProductViewController::class, 'remove'])->name('remove.from.cart');
Route::get('/home',function(){
    return redirect('/');
})->name('home');
// route for admin
Route::resource('product-order', App\Http\Controllers\ProductOrderController::class);
Route::resource('brand', App\Http\Controllers\ModelController::class);
Route::resource('dashboard', App\Http\Controllers\DashboardController::class);
Route::resource('product-list', ProductViewController::class);
Route::resource('products', App\Http\Controllers\ProductController::class);
Route::resource('cart', App\Http\Controllers\CartController::class);
Route::resource('contact-us', App\Http\Controllers\ContactController::class);
Route::resource('contacts', App\Http\Controllers\ContactBackEndController::class);
Route::resource('users', App\Http\Controllers\UserController::class);
   
Route::get('stripe', [StripeController::class, 'stripe']);
Route::post('stripe', [StripeController::class, 'stripePost'])->name('stripe.post');

resources/views/pages/fronts/cart.blade.php
@extends('layouts.app')
@section("content")
    <div class="container">
        <table class="table table-striped table-horvered table-bordered" id="datatablesSimple">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Product</th>
                    <th>Price</th>
                    <th>Quantity</th>
                    <th>Subtotal</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @php $total = 0 @endphp
                @if(session('cart'))
                    @foreach(session('cart') as $id => $details)
                        @php $total += $details['price'] * $details['quantity'] @endphp
                        <tr data-id="{{ $id }}">
                            <td data-th="Product">
                                <div class="row">
                                    <div class="col-sm-3 hidden-xs"><img src="{{ asset("/images/products/".$details['image']) }}" width="60%" class="img-responsive"/></div>
                                    <div class="col-sm-9">
                                        <h6 class="nomargin">{{ $details['name'] }}</h6>
                                    </div>
                                </div>
                            </td>
                            <td data-th="Price">${{ $details['price'] }}</td>
                            <td data-th="Quantity">
                                <input type="number" value="{{ $details['quantity'] }}" class="form-control quantity update-cart" />
                            </td>
                            <td data-th="Subtotal" class="text-center">${{ $details['price'] * $details['quantity'] }}</td>
                            <td class="actions" data-th="">
                                <button class="btn btn-danger btn-sm remove-from-cart"><i class="fa fa-trash"></i></button>
                            </td>
                        </tr>
                    @endforeach
                @endif
            </tbody>
            <tfoot>
                <tr>
                    <td colspan="6" class="text-right"><h4><strong>Total ${{ $total }}</strong></h4></td>
                </tr>
                <tr>
                    <td colspan="6" class="text-right">
                        <a href="{{ url('/') }}" class="btn btn-warning btn-sm">
                            <i class="fa fa-angle-left"></i> Continue Shopping
                        </a>
                        <a href="{{ url('stripe')}}" class="btn btn-sm btn-success">Checkout</a>
                        {{-- <a href="{{ route('cart.checkout')}}" class="btn btn-sm btn-success">Checkout</a> --}}
                    </td>
                </tr>
            </tfoot>
        </table>
    </div>
@endsection
@push('scripts')
    <script type="text/javascript">
       $(".update-cart").change(function (e) {
            e.preventDefault();
            var ele = $(this);
            $.ajax({
                url: '{{ route('update.cart') }}',
                method: "patch",
                data: {
                    _token: '{{ csrf_token() }}', 
                    id: ele.parents("tr").attr("data-id"), 
                    quantity: ele.parents("tr").find(".quantity").val()
                },
                success: function (response) {
                    window.location.reload();
                }
            });
        });
        $(".remove-from-cart").click(function (e) {
            e.preventDefault();
            var ele = $(this);
            if(confirm("Are you sure want to remove?")) {
                $.ajax({
                    url: '{{ route('remove.from.cart') }}',
                    method: "DELETE",
                    data: {
                        _token: '{{ csrf_token() }}', 
                        id: ele.parents("tr").attr("data-id")
                    },
                    success: function (response) {
                        window.location.reload();
                    }
                });
            }
        });
    </script>
@endpush

resources/views/pages/fronts/contact.blade.php
<style>
    textarea#message{
        height: 100px;
    }
</style>
@extends('layouts.app')
@section('content')
    <div class="banner-content">
        <img src="{{ asset("/images/banner/banner1.jpg") }}" alt="Image banner" width="100%">
    </div>
    <div class="container">
        <h4>Contact Us</h4>
        <hr>
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-body">
                        <form action="{{ route("contact-us.store") }}" method="POST">
                            @csrf
                            @method("POST")
                            <div class="form-group">
                                <label for="username">Username</label>
                                <input type="text" name="username" id="username" placeholder="Username"
                                @if (Auth::check())
                                    value="{{ Auth::user()->name }}"
                                @endif
                                 class="form-control">
                                @if ($errors->has('username'))
                                    <span class="text-danger">
                                        <strong>{{ $errors->first('username') }}</strong>
                                    </span>
                                @endif
                            </div>
                            <div class="form-group">
                                <label for="email">Email</label>
                                <input type="email" name="email" id="email" placeholder="Email"
                                @if (Auth::check())
                                    value="{{ Auth::user()->email }}"
                                @endif class="form-control">
                                @if ($errors->has('email'))
                                    <span class="text-danger">
                                        <strong>{{ $errors->first('email') }}</strong>
                                    </span>
                                @endif
                            </div>
                            <div class="form-group">
                                <label for="subject">Subject</label>
                                <input type="text" name="subject" id="subject" placeholder="Subject" class="form-control">
                                @if ($errors->has('subject'))
                                    <span class="text-danger">
                                        <strong>{{ $errors->first('subject') }}</strong>
                                    </span>
                                @endif
                            </div>
                            <div class="form-group">
                                <label for="message">Message</label>
                                <textarea name="message" id="message" cols="10" rows="10" class="form-control"></textarea>
                                @if ($errors->has('message'))
                                    <span class="text-danger">
                                        <strong>{{ $errors->first('message') }}</strong>
                                    </span>
                                @endif
                            </div>
                            <button type="reset" class="btn btn-secondary float-left">Reset Form</button>
                            <button type="submit" class="btn btn-success float-right">Submit</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/pages/fronts/product.blade.php
@extends("layouts.app")
@section('content')
    <div class="banner-content">
        <img src="{{ asset("/images/banner/banner1.jpg") }}" alt="Image banner" width="100%">
    </div>
    <div class="container">
        <h2>Products Listing</h2>
        <hr>
        <div class="row mt-2">
            @foreach ($products as $product)
                <div class="col-md-3">
                    <div class="card">
                        <div class="card-body">
                            <img src="{{ asset("/images/products/".$product->image) }}" alt="Product Image" width="60%">
                            <h5>{{ $product->name }}</h5>
                            <p><small>
                                <span class="text-secondary"><b>Model: </b></span> 
                                <span class="text-warning">{{ $product->model->name }}</span>
                            </small></p>
                            <p><b>Price:</b> <span class="text-danger">${{ $product->price }}</span> 
                                <a href="#" data-toggle="modal" data-target="#product-detail" 
                                    data-cpu="{{ $product->cpu }}" data-id="{{ $product->id }}"
                                    data-name="{{ $product->name }}" data-price="{{ $product->price }}"
                                    data-model="{{ $product->model->name }}" data-screen="{{ $product->screen }}"
                                    data-color="{{ $product->color }}" data-ram="{{ $product->ram }}"
                                    data-type="{{ $product->type }}" data-storage="{{ $product->storage }}"
                                    data-image="{{ asset("/images/products/".$product->image) }}"
                                    class="text-secondary">
                                    <small>More Detail</small>
                                </a>
                            </p>
                            <a href="{{ route('add.to.cart', $product->id) }}" 
                                class="btn btn-sm bg-warning form-control btn-checkout">
                                <i class="fa fa-plus-circle"></i> Add to cart
                            </a>
                        </div>
                    </div>
                </div>
            @endforeach
        </div>
    </div>
    <div class="modal fade" id="product-detail" tabindex="-1" role="dialog">
        <div class="modal-dialog modal-lg" role="document">
            <div class="modal-content ">
                <div class="modal-body">
                    <div class="row">
                        <div class="col-md-6">
                            <img src="" id="image" width="90%">
                            <h3 id="product-name"></h3>
                            <p>Model: <small id="model" class="text-warning"></small></p>
                        </div>
                        <div class="col-md-6">
                            <ul class="list-group">
                                <li class="list-group-item d-flex justify-content-between align-items-center">
                                  RAM:
                                  <span id="ram"></span>
                                </li>
                                <li class="list-group-item d-flex justify-content-between align-items-center">
                                  Color:
                                  <span id="color"></span>
                                </li>
                                <li class="list-group-item d-flex justify-content-between align-items-center">
                                  Screen:
                                  <span id="screen"></span>
                                </li>
                                <li class="list-group-item d-flex justify-content-between align-items-center">
                                  CPU:
                                  <span id="cpu"></span>
                                </li>
                                <li class="list-group-item d-flex justify-content-between align-items-center">
                                  Storage:
                                  <span id="storage"></span>
                                </li>
                                <li class="list-group-item d-flex justify-content-between align-items-center">
                                  Price:
                                  <span id="price"></span>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@push('scripts')
    <script>
        $(document).ready(function(){
            $('#product-detail').on('show.bs.modal',function (event){
                var button = $(event.relatedTarget)
                var id = button.data('id');
                var name = button.data('name');
                var model = button.data('model');
                var proImage = button.data('image');
                var ram = button.data('ram');
                var color = button.data('color');
                var storage = button.data('storage');
                var screen = button.data('screen');
                var type = button.data('type');
                var price = button.data('price');
                var cpu = button.data('cpu');
                var modal = $(this);
                $('#product-name').text(name);
                $('#ram').text(ram);
                $('#color').text(color);
                $('#screen').text(screen);
                $('#type').text(type);
                $('#storage').text(storage);
                $('#cpu').text(cpu);
                $('#price').text("$"+price);
                $('#model').text(model);
                $('#image').attr('src',proImage);
            });
        });
    </script>
@endpush

resources/views/pages/fronts/stripe.blade.php
<style type="text/css">
   .panel-title {
   display: inline;
   font-weight: bold;
   }
   .display-table {
   display: table;
   }
   .display-tr {
   display: table-row;
   }
   .display-td {
   display: table-cell;
   vertical-align: middle;
   width: 100%;
   }
</style>
@extends('layouts.app')
@section('content')
<div class="banner-content">
    <img src="{{ asset("/images/banner/banner1.jpg") }}" alt="Image banner" width="100%">
</div>
<div class="container">
    <h4>Stripe Payment Gateway</h4>
    <hr>
    <div class="row justify-content-center">
        <div class="col-md-6 col-md-offset-3">
            <div class="card mb-3">
                <div class="panel panel-default credit-card-box">
                    <div class="card-header">
                        <div class="row">
                            <div class="col-md-6">
                                <h5>Payment Details</h5>
                            </div>
                            <div class="col-md-6">
                                <img class="img-responsive pull-right" src="{{ asset("images/logo/payment-method.jpg") }}" width="60%">
                            </div>
                        </div>
                    </div>
                    <div class="card-body">
                        <div class="panel-body">
                            @if (Session::has('success'))
                            <div class="alert alert-success text-center">
                                <a href="#" class="close" data-dismiss="alert" aria-label="close">×</a>
                                <p>{{ Session::get('success') }}</p>
                            </div>
                            @endif
                            <form role="form" action="{{ route('stripe.post') }}" method="post" class="require-validation" data-cc-on-file="false" data-stripe-publishable-key="{{ env('STRIPE_KEY') }}" id="payment-form">
                                @csrf
                                <div class='form-row row'>
                                    <div class='col-md-6 form-group required'>
                                        <label class='control-label'>Name on Card</label> <input class='form-control' name="card_holder_name" size='4' type='text'>
                                    </div>
                                    <div class='col-md-6 form-group required'>
                                        <label class='control-label'>Card Number</label> <input autocomplete='off' name="card_holder_number" class='form-control card-number' size='20' type='text'>
                                    </div>
                                </div>
                                <div class='form-row row'>
                                    <div class='col-xs-12 col-md-4 form-group cvc required'>
                                        <label class='control-label'>CVC</label> <input autocomplete='off' class='form-control card-cvc' placeholder='ex. 311' size='4' type='text'>
                                    </div>
                                    <div class='col-xs-12 col-md-4 form-group expiration required'>
                                        <label class='control-label'>Expiration Month</label> <input class='form-control card-expiry-month' placeholder='MM' size='2' type='text'>
                                    </div>
                                    <div class='col-xs-12 col-md-4 form-group expiration required'>
                                        <label class='control-label'>Expiration Year</label> <input class='form-control card-expiry-year' placeholder='YYYY' size='4' type='text'>
                                    </div>
                                </div>
                                <div class='form-row row'>
                                    <div class='col-md-12 error form-group hide'>
                                        <div class='alert-danger alert'>Please correct the errors and try
                                            again.</div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-xs-12">
                                        <button class="btn btn-primary btn-lg btn-block" type="submit">Pay Now (${{$totalAmount}})</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection
@push('scripts')
<script type="text/javascript" src="https://js.stripe.com/v2/"></script>
<script type="text/javascript">
$(function() {
    var $form = $(".require-validation");
    $('form.require-validation').bind('submit', function(e) {
        var $form = $(".require-validation"),
            inputSelector = ['input[type=email]', 'input[type=password]',
                'input[type=text]', 'input[type=file]',
                'textarea'
            ].join(', '),
            $inputs = $form.find('.required').find(inputSelector),
            $errorMessage = $form.find('div.error'),
            valid = true;
        $errorMessage.addClass('hide');

        $('.has-error').removeClass('has-error');
        $inputs.each(function(i, el) {
            var $input = $(el);
            if ($input.val() === '') {
                $input.parent().addClass('has-error');
                $errorMessage.removeClass('hide');
                e.preventDefault();
            }
        });

        if (!$form.data('cc-on-file')) {
            e.preventDefault();
            Stripe.setPublishableKey($form.data('stripe-publishable-key'));
            Stripe.createToken({
                number: $('.card-number').val(),
                cvc: $('.card-cvc').val(),
                exp_month: $('.card-expiry-month').val(),
                exp_year: $('.card-expiry-year').val()
            }, stripeResponseHandler);
        }

    });

    function stripeResponseHandler(status, response) {
        if (response.error) {
            $('.error')
                .removeClass('hide')
                .find('.alert')
                .text(response.error.message);
        } else {
            // token contains id, last4, and card type
            var token = response['id'];
            // insert the token into the form so it gets submitted to the server
            $form.find('input[type=text]').empty();
            $form.append("<input type='hidden' name='stripeToken' value='" + token + "'/>");
            $form.get(0).submit();
        }
    }

});
</script>
@endpush