routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ProductViewController;
use App\Http\Controllers\CheckoutController;
use App\Http\Controllers\ChangePasswordController;
use App\Http\Controllers\UpdateProfileController;
use App\Http\Controllers\StripeController;
use App\Models\Product;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    $products = Product::orderBy("created_at",'desc')->take(8)->get();
    return view('home',compact('products'));
});

Auth::routes();
Route::get("admin",function(){
    return redirect("dashboard");
});
// change password
Route::resource('change-password', ChangePasswordController::class);
// update profile
Route::get('/update-profile/{user}',  [UpdateProfileController::class, 'editProfile'])->name("profile.edit");
Route::patch('/update-profile/{user}',  [UpdateProfileController::class, 'updateProfile'])->name('profile.update');

// routes for make ordering front pages
Route::get('/checkout', [CheckoutController::class, 'checkout'])->name('cart.checkout');
Route::get('add-to-cart/{id}', [ProductViewController::class, 'addToCart'])->name('add.to.cart');
Route::patch('update-cart', [ProductViewController::class, 'update'])->name('update.cart');
Route::delete('remove-from-cart', [ProductViewController::class, 'remove'])->name('remove.from.cart');
Route::get('/home',function(){
    return redirect('/');
})->name('home');
// route for admin
Route::resource('product-order', App\Http\Controllers\ProductOrderController::class);
Route::resource('brand', App\Http\Controllers\ModelController::class);
Route::resource('dashboard', App\Http\Controllers\DashboardController::class);
Route::resource('product-list', ProductViewController::class);
Route::resource('products', App\Http\Controllers\ProductController::class);
Route::resource('cart', App\Http\Controllers\CartController::class);
Route::resource('contact-us', App\Http\Controllers\ContactController::class);
Route::resource('contacts', App\Http\Controllers\ContactBackEndController::class);
Route::resource('users', App\Http\Controllers\UserController::class);
   
Route::get('stripe', [StripeController::class, 'stripe']);
Route::post('stripe', [StripeController::class, 'stripePost'])->name('stripe.post');

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    use HasFactory;
    protected $table='products';
    protected $primarykey='id';
    protected $fillable = [
        'name','screen','price','image','color','type','ram','hard_disk','cpu','model_id'
    ];

    // // relationship many products belongs to many users
    // public function users(){
    //     return $this->belongsToMany(User::class,'user_id');
    // }
    // relationship many products belongs to one brand
    public function model(){
        return $this->belongsTo(Brand::class,'model_id');
    }
    
    public function orders()
    {
        return $this->belongsToMany(Order::class,'order_items');
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Product;
use App\Models\Brand;
use Validator;
use Illuminate\Support\Facades\Storage;
class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function __construct()
    {
        $this->middleware('auth');
        $this->middleware('role:admin');
    }
    public function index()
    {
        $index = 1;
        $products = Product::orderBy("created_at",'desc')->get();
        return view("pages.admin.products.product",compact("index","products"));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $models = Brand::orderBy("name",'asc')->get();
        return view("pages.admin.products.add",compact('models'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validator = Validator::make($request->all(),[
            'name' => 'required',
            'price' => 'required',
            'color' => 'required',
            'ram' => 'required',
            'cpu' => 'required',
            'screen' => 'required',
            'storage' => 'required',
            'image' => 'required',
            'model_id' => 'required'
        ]);
        if ($validator->fails()) {
            return redirect()->back()->withErrors($validator)->withInput($request->input());
        }

        if ($request->hasFile("image")) {
            $products = new Product();
            $products->name = $request->name;
            $products->price = $request->price;
            $products->color = $request->color;
            $products->ram = $request->ram;
            $products->cpu = $request->cpu;
            $products->storage = $request->storage;
            $products->screen = $request->screen;
            $products->model_id = $request->model_id;

            $path = '/images/products/';
            $proImage = $request->file("image")->getClientOriginalName();
             $request->file("image")->move(public_path($path), $proImage);
            // $request->file('image')->storeAs($path, $proImage);
            $products->image = $proImage;

            $products->save();
            return redirect('products')->with("success","Product created successfully!");
        }else{
            return redirect()->back()->with("error","Product fail created!");
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $product = Product::findOrFail($id);
        return view("pages.admin.products.view",compact("product"));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $models = Brand::orderBy("name",'asc')->get();
        $product = Product::findOrFail($id);
        return view("pages.admin.products.edit",compact('product','models'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $validator = Validator::make($request->all(),[
            'name' => 'required',
            'price' => 'required',
            'color' => 'required',
            'ram' => 'required',
            'cpu' => 'required',
            'screen' => 'required',
            'storage' => 'required',
            'model_id' => 'required'
        ]);
        if ($validator->fails()) {
            return redirect()->back()->withErrors($validator)->withInput($request->input());
        }
        $product = Product::findOrFail($id);
        $product->name = $request->name;
        $product->price = $request->price;
        $product->color = $request->color;
        $product->ram = $request->ram;
        $product->cpu = $request->cpu;
        $product->screen = $request->screen;
        $product->storage = $request->storage;
        $product->model_id = $request->model_id;

        if ($request->hasFile("image")) {
            $path = '/images/products/';
            $proImage = $request->file("image")->getClientOriginalName();
            // $request->file('image')->storeAs($path, $proImage);
            $request->file("image")->move(public_path($path), $proImage);
            $product->image = $proImage;

            $product->save();
            return redirect('products')->with("success","Product updated successfully!");
        }else{
            $product->image = $product->image;
            $product->save();
            return redirect("products")->with("success","Product updated successfully !");
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $product = Product::findOrFail($id);
        $product->delete();
        return redirect()->back()->with('success','Product deleted successfully !');
    }
}

resources/views/pages/admin/products/add.blade.php
<style>
    #description{
        height: 60px;
    }
</style>
@extends('layouts.dashboard')
@section('dashboard')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-6">
                @if ($message = Session::get('warning'))
                    <div class="alert alert-warning alert-block">
                        <strong>{{ $message }}</strong>
                    </div>
                @endif
            </div>
        </div>
        <div class="row justify-content-center">
            <div class="col-md-1-">
                <div class="card">
                    <div class="card-header">
                        <h4>Create Product</h4>
                    </div>
                    <div class="card-body">
                        <form action="{{ route("products.store") }}" method="POST" enctype="multipart/form-data">
                            @csrf
                            @method("POST")
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group mt-2">
                                        <label for="name">Product Name</label>
                                        <input type="text" name="name" id="name" class="form-control"
                                        placeholder="Product Name">
                                        @if ($errors->has('name'))
                                            <span class="text-danger">
                                                <strong>{{ $errors->first('name') }}</strong>
                                            </span>
                                        @endif
                                    </div>
                                    <div class="form-group mt-2">
                                        <label for="price">Price</label>
                                        <input type="text" name="price" id="price" class="form-control"
                                        placeholder="Price">
                                        @if ($errors->has('price'))
                                            <span class="text-danger">
                                                <strong>{{ $errors->first('price') }}</strong>
                                            </span>
                                        @endif
                                    </div>
                                    <div class="form-group mt-2">
                                        <label for="image">Product Image</label>
                                        <input type="file" name="image" id="image" class="form-control"
                                        placeholder="Product Image">
                                        @if ($errors->has('image'))
                                            <span class="text-danger">
                                                <strong>{{ $errors->first('image') }}</strong>
                                            </span>
                                        @endif
                                    </div>
                                    <div class="form-group mt-2">
                                        <label for="model">Product Model</label>
                                        <select name="model_id" id="model" class="form-control">
                                            <option disabled selected>Select Model</option>
                                            @foreach ($models as $model)
                                                <option value="{{ $model->id }}">{{ $model->name }}</option>
                                            @endforeach
                                        </select>
                                        @if ($errors->has('model_id'))
                                            <span class="text-danger">
                                                <strong>{{ $errors->first('model_id') }}</strong>
                                            </span>
                                        @endif
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group mt-2">
                                        <label for="color">Color</label>
                                        <input type="text" name="color" id="color" class="form-control"
                                        placeholder="Color">
                                        @if ($errors->has('color'))
                                            <span class="text-danger">
                                                <strong>{{ $errors->first('color') }}</strong>
                                            </span>
                                        @endif
                                    </div>
                                    <div class="form-group mt-2">
                                        <label for="screen">Screen</label>
                                        <input type="text" name="screen" id="screen" class="form-control"
                                        placeholder="Screen">
                                        @if ($errors->has('screen'))
                                            <span class="text-danger">
                                                <strong>{{ $errors->first('screen') }}</strong>
                                            </span>
                                        @endif
                                    </div>
                                    <div class="form-group mt-2">
                                        <label for="ram">RAM</label>
                                        <input type="text" name="ram" id="ram" class="form-control"
                                        placeholder="RAM">
                                        @if ($errors->has('ram'))
                                            <span class="text-danger">
                                                <strong>{{ $errors->first('ram') }}</strong>
                                            </span>
                                        @endif
                                    </div>
                                    <div class="form-group mt-2">
                                        <label for="cpu">CPU</label>
                                        <input type="text" name="cpu" id="cpu" class="form-control"
                                        placeholder="CPU">
                                        @if ($errors->has('cpu'))
                                            <span class="text-danger">
                                                <strong>{{ $errors->first('cpu') }}</strong>
                                            </span>
                                        @endif
                                    </div>
                                    <div class="form-group mt-2">
                                        <label for="storage">Storage</label>
                                        <input type="text" name="storage" id="storage" class="form-control"
                                        placeholder="Storage">
                                        @if ($errors->has('storage'))
                                            <span class="text-danger">
                                                <strong>{{ $errors->first('storage') }}</strong>
                                            </span>
                                        @endif
                                    </div>
                                </div>
                            </div>
                            <div class="form-group mt-4">
                                <a href="{{ url("products") }}" class="btn btn-secondary">Cancel</a>
                                <button type="submit" class="btn btn-success float-right">Create</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/pages/admin/products/edit.blade.php
<style>
    #description{
        height: 60px;
    }
</style>
@extends('layouts.dashboard')
@section('dashboard')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-6">
                @if ($message = Session::get('warning'))
                    <div class="alert alert-warning alert-block">
                        <strong>{{ $message }}</strong>
                    </div>
                @endif
            </div>
        </div>
        <div class="row justify-content-center">
            <div class="col-md-1-">
                <div class="card">
                    <div class="card-header">
                        <h4>Update Product</h4>
                    </div>
                    <div class="card-body">
                        <form action="{{ route("products.update",$product->id) }}" method="POST" enctype="multipart/form-data">
                            @csrf
                            @method("PATCH")
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group mt-2">
                                        <label for="name">Product Name</label>
                                        <input type="text" name="name" id="name" class="form-control"
                                        value="{{ $product->name }}" placeholder="Product Name">
                                        @if ($errors->has('name'))
                                            <span class="text-danger">
                                                <strong>{{ $errors->first('name') }}</strong>
                                            </span>
                                        @endif
                                    </div>
                                    <div class="form-group mt-2">
                                        <label for="price">Price</label>
                                        <input type="text" name="price" id="price" class="form-control"
                                        value="{{ $product->price }}" placeholder="Price">
                                        @if ($errors->has('price'))
                                            <span class="text-danger">
                                                <strong>{{ $errors->first('price') }}</strong>
                                            </span>
                                        @endif
                                    </div>
                                    <div class="form-group mt-2">
                                        <label for="image">Product Image</label>
                                        <input type="file" name="image" id="image" class="form-control"
                                        value="{{ $product->image }}" placeholder="Product Image">
                                        @if ($errors->has('image'))
                                            <span class="text-danger">
                                                <strong>{{ $errors->first('image') }}</strong>
                                            </span>
                                        @endif
                                    </div>
                                    <div class="form-group mt-2">
                                        <label for="model">Product Model</label>
                                        <select name="model_id" id="model" class="form-control">
                                            <option disabled selected>Select Model</option>
                                            @foreach ($models as $model)
                                                <option value="{{ $model->id }}"
                                                    @if ($product->model_id == $model->id)
                                                        selected
                                                    @endif>
                                                    {{ $model->name }}
                                                </option>
                                            @endforeach
                                        </select>
                                        @if ($errors->has('model_id'))
                                            <span class="text-danger">
                                                <strong>{{ $errors->first('model_id') }}</strong>
                                            </span>
                                        @endif
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group mt-2">
                                        <label for="color">Color</label>
                                        <input type="text" name="color" id="color" class="form-control"
                                        value="{{ $product->color }}" placeholder="Color">
                                        @if ($errors->has('color'))
                                            <span class="text-danger">
                                                <strong>{{ $errors->first('color') }}</strong>
                                            </span>
                                        @endif
                                    </div>
                                    <div class="form-group mt-2">
                                        <label for="screen">Screen</label>
                                        <input type="text" name="screen" id="screen" class="form-control"
                                        value="{{ $product->screen }}" placeholder="Screen">
                                        @if ($errors->has('screen'))
                                            <span class="text-danger">
                                                <strong>{{ $errors->first('screen') }}</strong>
                                            </span>
                                        @endif
                                    </div>
                                    <div class="form-group mt-2">
                                        <label for="ram">RAM</label>
                                        <input type="text" name="ram" id="ram" class="form-control"
                                        value="{{ $product->ram }}" placeholder="RAM">
                                        @if ($errors->has('ram'))
                                            <span class="text-danger">
                                                <strong>{{ $errors->first('ram') }}</strong>
                                            </span>
                                        @endif
                                    </div>
                                    <div class="form-group mt-2">
                                        <label for="cpu">CPU</label>
                                        <input type="text" name="cpu" id="cpu" class="form-control"
                                        value="{{ $product->cpu }}" placeholder="CPU">
                                        @if ($errors->has('cpu'))
                                            <span class="text-danger">
                                                <strong>{{ $errors->first('cpu') }}</strong>
                                            </span>
                                        @endif
                                    </div>
                                    <div class="form-group mt-2">
                                        <label for="storage">Storage</label>
                                        <input type="text" name="storage" id="storage" class="form-control"
                                        value="{{ $product->storage }}" placeholder="Storage">
                                        @if ($errors->has('storage'))
                                            <span class="text-danger">
                                                <strong>{{ $errors->first('storage') }}</strong>
                                            </span>
                                        @endif
                                    </div>
                                </div>
                            </div>
                            <div class="form-group mt-4">
                                <a href="{{ url("products") }}" class="btn btn-secondary">Cancel</a>
                                <button type="submit" class="btn btn-success float-right">Update</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/pages/admin/products/product.blade.php
@extends('layouts.dashboard')
@section('dashboard')
    <div class="row justify-content-center">
        <div class="col-md-5">
            @if ($message = Session::get('success'))
                <div class="alert alert-success alert-block">
                    <strong>{{ $message }}</strong>
                </div>
            @endif
            @if ($message = Session::get('error'))
                <div class="alert alert-danger alert-block">
                    <strong>{{ $message }}</strong>
                </div>
            @endif
        </div>
    </div>
    <div class="row">
        <div class="col-md-10">
            <h4>Products Listing</h4>
        </div>
        <div class="col-md-2 mr-auto">
            <a href="{{ route("products.create") }}" class="btn btn-sm btn-primary float-right">
                <i class="fa fa-plus-circle"></i> Add Product
            </a>
        </div>
    </div>
    <table class="table table-striped table-horvered table-bordered mt-3" id="datatablesSimple">
        <thead>
            <tr>
                <th>#</th>
                <th>Product Name</th>
                <th>Brand</th>
                <th>Price</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($products as $product)
                <tr>
                    <td width="5%">{{ $index++ }}</td>
                    <td width="40%">
                        <img src="{{ asset("/images/products/".$product->image) }}" alt="" width="5%">
                        <span>{{ $product->name }}</span>
                    </td>
                    <td width="15%">{{ $product->model->name }}</td>
                    <td width="15%">${{ $product->price }}.00</td>
                    <td width="10%">
                        <a href="{{ route("products.show",$product->id) }}">
                            <i class="fas fa-eye fa-fw text-primary"></i>
                        </a>
                        <a href="#" data-toggle="modal" data-target="#delete-product" 
                            data-id="{{ $product->id }}" data-name="{{ $product->name }}"
                            data-model="{{ $product->model->name }}"
                            data-image="{{ asset("/images/products/".$product->image) }}">
                            <i class="fas fa-trash-alt fa-fw text-danger"></i>
                        </a>
                        <a href="{{ route("products.edit",$product->id) }}">
                            <i class="fas fa-pencil-alt fa-fw text-success"></i>
                        </a>
                    </td>
                </tr>
            @endforeach
        </tbody>
    </table>
    <div class="modal fade" id="delete-product" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <form action="" method="POST" id="form-delete-product" enctype="multipart/form-data">
                    @method('DELETE')
                    @csrf
                    <div class="modal-header">
                        <h4 class="modal-title" id="deleteProductLabel">Delete Product</h4>
                    </div>
                    <div class="modal-body">
                        <p>Do you sure to <b>delete</b> <b><span class="text-danger" id="product-name"></span></b> ?</p>
                        <div class="text-center">
                            <img src="" alt="" width="50%" id="product-image" class="text-center">
                        </div>
                        <p>Model:<span id="model-name"></span></p>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-link waves-effect text-white btn-success float-left" data-dismiss="modal">No</button>
                        <button type="submit" class="btn btn-link btn-danger text-white waves-effect float-right">Yes</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection
@push('script')
    <script>
        $(document).ready(function(){
            $('#delete-product').on('show.bs.modal',function (event){
                var button = $(event.relatedTarget)
                var id = button.data('id');
                var proName = button.data('name');
                var modelName = button.data('model');
                var proImage = button.data('image');
                var modal = $(this);
                var url ='{{ route("products.destroy", "id") }}';
                $('#product-name').text(proName);
                $('#model-name').text(modelName);
                $('#product-image').attr('src',proImage);
                $('#form-delete-product').attr('action',url.replace('id', id));
            });
        });
    </script>
@endpush